title: Papaya Blogy
description: Tu nájdete všetky blogy z Česko-Slovenského Discord serveru Papaya

url: "https://PapayaTravel.github.io"      # ← ZMEŇ na svoj GitHub username!
baseurl: "/Papaya-Blogy"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

show_excerpts: true
search: true

# === VZHĽAD ===
minimal_mistakes_skin: "default"

# Farby
primary-color: "#f4e9d8"        # krémové pozadie
accent-color: "#e67e22"         # oranžová (papaya štýl)

# Header
header:
  overlay_color: "#ffffff"
  overlay_filter: 0.0
